---
- name: Install Apache centos docker
  hosts: server
  become: yes
  vars:
    dockerfile: /home/marcones.silva/github/Docker/centos-nginx

  tasks:
  - name: Remove previous images
    command: docker rm -f web
    ignore_errors: yes

  - name: Build images
    command: docker build -t mynginx {{ dockerfile }}

  - name: Create container
    command: docker run -i -d -p 8080:80 --name web -t mynginx
